### ISSUE TITLE
Need to revert SiglDev EC2 to run 24/7 for time being

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/SiGLServices#24]
Somehow the production app is pointing to sigldev and I need time to move the services application to the production server.   So until I get a chance to figure that out, can we keep the siglDev instance running 24/7?

**Comment by aaronstephenson** [comment]
Instance removed from the nightly shutdown list.

**Comment by HansVraga** [comment]
Looks like this could be closed - @esmyers are we still in this state?

**Comment by esmyers** [comment]
True. We no longer need this to be running.  I just turned it off and am closing the issue.
